import { UpsertInspectionItemStatus } from "@workspace/api-client-react";

export const INSPECTION_CATEGORIES = [
  "OBDII",
  "Engine",
  "Transmission",
  "Brakes",
  "Steering",
  "Suspension",
  "Tires",
  "Exterior",
  "Interior",
  "Electrical",
  "Fluids",
  "Engine Performance"
];

export const INSPECTION_TEMPLATE = [
  // OBDII
  { category: "OBDII", item: "Scan for codes" },
  { category: "OBDII", item: "Check engine light" },
  { category: "OBDII", item: "Pending codes" },
  { category: "OBDII", item: "Readiness monitors" },
  // Engine
  { category: "Engine", item: "Oil level" },
  { category: "Engine", item: "Coolant level" },
  { category: "Engine", item: "Air filter" },
  { category: "Engine", item: "Belts and hoses" },
  { category: "Engine", item: "Engine mounts" },
  { category: "Engine", item: "Valve cover/gaskets" },
  // Transmission
  { category: "Transmission", item: "Fluid level" },
  { category: "Transmission", item: "Shift quality" },
  { category: "Transmission", item: "Linkage" },
  // Brakes
  { category: "Brakes", item: "Front pads thickness" },
  { category: "Brakes", item: "Rear pads thickness" },
  { category: "Brakes", item: "Rotors condition" },
  { category: "Brakes", item: "Brake fluid" },
  { category: "Brakes", item: "Parking brake" },
  { category: "Brakes", item: "Brake lines" },
  // Steering
  { category: "Steering", item: "Steering wheel (play, binding, tilt)" },
  { category: "Steering", item: "Steering column / u-joints" },
  { category: "Steering", item: "Power steering pump" },
  { category: "Steering", item: "Power steering hoses / lines" },
  { category: "Steering", item: "Steering rack / gearbox" },
  { category: "Steering", item: "Inner tie rods" },
  { category: "Steering", item: "Outer tie rods" },
  { category: "Steering", item: "Steering knuckles" },
  // Suspension
  { category: "Suspension", item: "Upper control arms" },
  { category: "Suspension", item: "Lower control arms" },
  { category: "Suspension", item: "Upper ball joints" },
  { category: "Suspension", item: "Lower ball joints" },
  { category: "Suspension", item: "CV axle - front left" },
  { category: "Suspension", item: "CV axle - front right" },
  { category: "Suspension", item: "CV axle - rear left" },
  { category: "Suspension", item: "CV axle - rear right" },
  { category: "Suspension", item: "Wheel bearing - front left" },
  { category: "Suspension", item: "Wheel bearing - front right" },
  { category: "Suspension", item: "Wheel bearing - rear left" },
  { category: "Suspension", item: "Wheel bearing - rear right" },
  { category: "Suspension", item: "Struts / shocks - front" },
  { category: "Suspension", item: "Struts / shocks - rear" },
  { category: "Suspension", item: "Strut mounts / bearings" },
  { category: "Suspension", item: "Coil springs - front" },
  { category: "Suspension", item: "Coil springs - rear" },
  { category: "Suspension", item: "Sway bar links - front" },
  { category: "Suspension", item: "Sway bar links - rear" },
  { category: "Suspension", item: "Sway bar bushings" },
  { category: "Suspension", item: "Subframe / cradle mounts" },
  { category: "Suspension", item: "Air suspension compressor (if equipped)" },
  { category: "Suspension", item: "Air bags / air struts (if equipped)" },
  { category: "Suspension", item: "Air lines & fittings (if equipped)" },
  { category: "Suspension", item: "Height sensors (if equipped)" },
  { category: "Suspension", item: "Air suspension module (if equipped)" },
  // Tires
  { category: "Tires", item: "Front left tread" },
  { category: "Tires", item: "Front right tread" },
  { category: "Tires", item: "Rear left tread" },
  { category: "Tires", item: "Rear right tread" },
  { category: "Tires", item: "Spare tire" },
  { category: "Tires", item: "Tire pressure" },
  { category: "Tires", item: "Roadside kit (jack, rod, lug wrench)" },
  // Exterior
  { category: "Exterior", item: "Paint condition" },
  { category: "Exterior", item: "Windshield" },
  { category: "Exterior", item: "Front washer nozzle" },
  { category: "Exterior", item: "Rear washer nozzle" },
  { category: "Exterior", item: "Lights (headlights/taillights/signals)" },
  { category: "Exterior", item: "Wipers" },
  { category: "Exterior", item: "Body damage" },
  { category: "Exterior", item: "Door seals" },
  // Interior
  { category: "Interior", item: "Seat condition" },
  { category: "Interior", item: "Dashboard lights" },
  { category: "Interior", item: "A/C and heat" },
  { category: "Interior", item: "Radio/infotainment" },
  { category: "Interior", item: "Windows" },
  { category: "Interior", item: "Seatbelts" },
  // Electrical
  { category: "Electrical", item: "Battery condition" },
  { category: "Electrical", item: "Alternator output" },
  { category: "Electrical", item: "Fuses" },
  { category: "Electrical", item: "Horn" },
  { category: "Electrical", item: "Misc. electrical (shorts, bad grounds)" },
  // Fluids
  { category: "Fluids", item: "Power steering fluid" },
  { category: "Fluids", item: "Windshield washer fluid" },
  { category: "Fluids", item: "Differential fluid" },
  // Engine Performance
  { category: "Engine Performance", item: "Engine tune / calibration" },
  { category: "Engine Performance", item: "Spark plugs & ignition system" },
  { category: "Engine Performance", item: "Throttle body & response" },
  { category: "Engine Performance", item: "Mass air flow (MAF) sensor" },
  { category: "Engine Performance", item: "Fuel injectors" },
  { category: "Engine Performance", item: "Fuel pressure & pump" },
  { category: "Engine Performance", item: "Oxygen sensors (upstream/downstream)" },
  { category: "Engine Performance", item: "EGR valve / system (if equipped)" },
  { category: "Engine Performance", item: "Variable valve timing / VVT (if equipped)" },
  { category: "Engine Performance", item: "Variable intake manifold (if equipped)" },
  { category: "Engine Performance", item: "Turbocharger(s) (if equipped)" },
  { category: "Engine Performance", item: "Intercooler / charge air cooler (if equipped)" },
  { category: "Engine Performance", item: "Boost pipes & couplers (if equipped)" },
  { category: "Engine Performance", item: "Wastegate (if equipped)" },
  { category: "Engine Performance", item: "Blow-off / bypass valve (if equipped)" },
  { category: "Engine Performance", item: "Boost control solenoid (if equipped)" },
  { category: "Engine Performance", item: "Supercharger (if equipped)" },
  { category: "Engine Performance", item: "Supercharger belt & drive (if equipped)" },
  { category: "Engine Performance", item: "Nitrous system (if equipped)" },
  { category: "Engine Performance", item: "Nitrous solenoids (if equipped)" },
  { category: "Engine Performance", item: "Nitrous lines & fittings (if equipped)" },
  { category: "Engine Performance", item: "Nitrous bottle pressure (if equipped)" },
  { category: "Engine Performance", item: "Performance exhaust / headers (if equipped)" },
  { category: "Engine Performance", item: "Cold air / short ram intake (if equipped)" },
];

export function buildDefaultInspection() {
  return INSPECTION_TEMPLATE.map(t => ({
    ...t,
    status: UpsertInspectionItemStatus.pending,
    notes: ""
  }));
}
